# Generated by Django 4.2.5 on 2023-10-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stonecircles',
            options={'managed': False},
        ),
    ]
