# Generated by Django 4.2.5 on 2023-10-28 19:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awm_app', '0002_alter_stonecircles_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='StoneCircles',
        ),
    ]
